# Generated by Django 3.0.6 on 2020-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200525_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('desc', models.TextField(max_length=500)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='team',
            name='github',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
