# Generated by Django 3.0.6 on 2020-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200528_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='desc',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
