# Generated by Django 3.0.4 on 2020-06-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200528_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='github',
            new_name='twitter',
        ),
    ]
